apiVersion: v1
kind: Service
metadata:
  name: pact
  labels:
    app: pact
spec:
  ports:
    - port: 80
  selector:
    app: pact
    tier: frontend
  type: LoadBalancer
---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pact
  creationTimestamp: null
  labels:
    app: pact

spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pact
        tier: frontend
    spec:
      containers:
      - env:
        - name: PACT_BROKER_DATABASE_NAME
          value: pactbroker
        - name: PACT_BROKER_DATABASE_PASSWORD
          value: TheUserPassword
        - name: PACT_BROKER_DATABASE_HOST
          value: pact-postgres
        - name: PACT_BROKER_DATABASE_USERNAME
          value: pactbrokeruser
        - name: PACT_BROKER_BASIC_AUTH_USERNAME
          value: shanelee007
        - name: PACT_BROKER_BASIC_AUTH_PASSWORD
          value: password123
        image: dius/pact-broker:latest
        name: pact
        ports:
        - containerPort: 80
      restartPolicy: Always
